### ISSUE TITLE
No author info in the Copilot post

### ISSUE THREAD

**Issue by Realvincentyuan** [BulletTech/BulletTech#25]
**Describe the bug**

No author info in the [Copilot post
](https://github.com/BulletTech/BulletTech/blob/main/docs/Dessert/Apps/2021-07-19-Copilot.md#%E5%91%8A%E5%88%AB%E9%9D%A2%E5%90%91google%E7%BC%96%E7%A8%8Bcopilot%E6%B5%8B%E8%AF%95%E7%89%88%E6%9C%AC%E4%BD%93%E9%AA%8C)

**To Reproduce**

**Expected behavior**

Add author info like other posts

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jz263** [comment]
Fixed in commit 156c8e2ce0ad7a791ccc8b8b56a44faced7d7331
